default_context:
    full_name: X Author Name
    email: x-pt@example.com
    github_username: x-pt
    project_name: Example Go
    project_slug: example-go
    package_name: example_go
    project_desc: A nice example project
    project_version: 0.0.1
    license: "MIT"

    # Go
    go_version: 1.22
