name: CI # Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-check:
    name: Lint and Format Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

{% if cookiecutter.cxx_build_tool == "xmake" %}
      - name: Setup XMake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
{% endif %}

      - name: Initialize Project (Setup Pre-commit)
        run: make init

      - name: Check Formatting and Linting (via pre-commit)
        run: pre-commit run --all-files --show-diff-on-failure

  build-and-test:
    name: Build and Test on {{ '${{ matrix.os }}' }}
    runs-on: {{ '${{ matrix.os }}' }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

{% if cookiecutter.cxx_build_tool == "xmake" %}
      - name: Setup XMake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
{% endif %}

      - name: Initialize Project
        run: make init

      - name: Build Project
        run: make build

      - name: Run Tests
        run: make test

      - name: Smoke Test (Run Application)
        run: make run
