FROM golang:{{cookiecutter.go_version}}-alpine AS builder

LABEL author="{{cookiecutter.full_name}}"

# Set necessary environmet variables needed for our image
# Such as:
# ENV GO111MODULE=on
# ENV CGO_ENABLED=0
# ENV GOOS=linux
# ENV GOARCH=amd64
