name: Examples

on:
    push:
        branches: [ main ]
    workflow_dispatch:  # Allow the workflow to be triggered manually

jobs:
    deployment:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                config:
                    -   name: cuda cmake example
                        template_dir: template/cuda
                        config_file: .github/configs/template_inputs_cuda_cmake.yml
                        publish_dir: example-cuda-cmake
                        repo_name: x-pt/example-cuda-cmake
                    -   name: cuda xmake example
                        template_dir: template/cuda
                        config_file: .github/configs/template_inputs_cuda_xmake.yml
                        publish_dir: example-cuda-xmake
                        repo_name: x-pt/example-cuda-xmake
                    -   name: cxx cmake example
                        template_dir: template/cxx
                        config_file: .github/configs/template_inputs_cxx_cmake.yml
                        publish_dir: example-cxx-cmake
                        repo_name: x-pt/example-cxx-cmake
                    -   name: cxx xmake example
                        template_dir: template/cxx
                        config_file: .github/configs/template_inputs_cxx_xmake.yml
                        publish_dir: example-cxx-xmake
                        repo_name: x-pt/example-cxx-xmake
                    -   name: python example
                        template_dir: template/py
                        config_file: .github/configs/template_inputs_py.yml
                        publish_dir: example-py
                        repo_name: x-pt/example-py
                    -   name: go example
                        template_dir: template/go
                        config_file: .github/configs/template_inputs_go.yml
                        publish_dir: example-go
                        repo_name: x-pt/example-go
                    -   name: rust example
                        template_dir: template/rs
                        config_file: .github/configs/template_inputs_rs.yml
                        publish_dir: example-rs
                        repo_name: x-pt/example-rs
                    -   name: typescript example
                        template_dir: template/ts
                        config_file: .github/configs/template_inputs_ts.yml
                        publish_dir: example-ts
                        repo_name: x-pt/example-ts

        steps:
            -   uses: actions/checkout@v4

            -   name: Setup CookieCutter
                run: pipx install cookiecutter

            -   name: Generate ${{ matrix.config.name }}
                run: cookiecutter --no-input --config-file ${{ matrix.config.config_file }} ${{ matrix.config.template_dir }}

            -   name: Push to ${{ matrix.config.repo_name }}
                uses: peaceiris/actions-gh-pages@v4
                with:
                    deploy_key: ${{ secrets.GH_EXAMPLE_DEPLOY_SECRET }}
                    external_repository: ${{ matrix.config.repo_name }}
                    publish_branch: main
                    publish_dir: ./${{ matrix.config.publish_dir }}
                    exclude_assets: ''
                    enable_jekyll: true
                    user_name: 'github-actions[bot]'
                    user_email: 'github-actions[bot]@users.noreply.github.com'
                    full_commit_message: "ci: Update ${{ matrix.config.name }}"
                    force_orphan: true
